//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronomy.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AstronomicalBodies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AstronomicalBodies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Astronomy.Resources.Languages.AstronomicalBodies", typeof(AstronomicalBodies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age_Label {
            get {
                return ResourceManager.GetString("Age_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billon.
        /// </summary>
        internal static string Billons_Convert {
            get {
                return ResourceManager.GetString("Billons_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circumference.
        /// </summary>
        internal static string Circumference_Label {
            get {
                return ResourceManager.GetString("Circumference_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        internal static string Earth_Name {
            get {
                return ResourceManager.GetString("Earth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halley&apos;s Comet.
        /// </summary>
        internal static string Halley_Name {
            get {
                return ResourceManager.GetString("Halley_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        internal static string Mass_Label {
            get {
                return ResourceManager.GetString("Mass_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon.
        /// </summary>
        internal static string Moon_Name {
            get {
                return ResourceManager.GetString("Moon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sun (Sol).
        /// </summary>
        internal static string Sun_Name {
            get {
                return ResourceManager.GetString("Sun_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomical Bodies.
        /// </summary>
        internal static string Title_Bodies {
            get {
                return ResourceManager.GetString("Title_Bodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomical Data.
        /// </summary>
        internal static string Title_Page {
            get {
                return ResourceManager.GetString("Title_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
